name: Run Azure SQL Command

on:
  # push:
  workflow_dispatch:
    inputs:
      queryString:
        description: "Query string"
        required: false
        default: "SELECT 1"
      returnResultFlag:
        description: "Flag indicating whether query result should be returned in JSON form"
        required: false
        default: "Yes"

jobs:
  azuresqlcmd-job:
    runs-on: ubuntu-latest
    name: Run Azure SQL Command
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Azure SQL Command
        id: azuresqlcmd
        uses: ./
        with:
          tenant_id: ${{ secrets.TENANT_ID }}
          service_principal_id: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          service_principal_secret: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          sql_server_name: ${{ secrets.SQL_SERVER_NAME }}
          sql_db_name: ${{ secrets.SQL_DB_NAME }}
          query_string: ${{ github.event.inputs.queryString }}
          return_result_flag: ${{ github.event.inputs.returnResultFlag }}
      - name: Get SQL Command output
        run: |
          echo "The SQL Command output ${{ steps.azuresqlcmd.outputs.count }}"
          # echo "The SQL Command output ${{ steps.azuresqlcmd.outputs.result }}"
